### ISSUE TITLE
Investigate random failures

### ISSUE THREAD

**Issue by PVince81** [owncloud/smashbox#172]
See public RocketChat #smashbox channel
@mrow4a

**Comment by mrow4a** [comment]
@PVince81 @DeepDiver1975 most of the failures are not related to owncloud server nor to client, but are because of testing infrastructure, and are transient. These below are only failed jobs for smashbox since 07.02>:

- failure on 1 test 19.02 (https://drone.owncloud.com/owncloud/smashbox-testing/429/736): drone timeout on oc server, transient CC @tboerger 

- failure on 1 test 13.02 (https://drone.owncloud.com/owncloud/smashbox-testing/423/152): This is real failure. 

Usually when test failes I check for WARNING in the smashbox, as this is early indicator of sth going wrong. I checked and for some reason client sync errored and did not finish, making whole test crash. No idea why client crashed, I have no access to the logs:
 
```
2019-02-13 01:51:18,067 - WARNING - shareeOne - Non-zero exit code 1 from command '/usr/bin/owncloudcmd --trust /smashdir/test_uploadFiles/shareeOne/ owncloud://test_uploadFiles2:owncloud@owncloud-server:8080/remote.php/webdav/ >> /smashdir/test_uploadFiles/shareeOne-ocsync.step06.cnt000.log 2>&1'
```

However, not sure if we can do much about random client crashes in the future.. I bet this happens in user environments too.

- failure on 5 tests 12.02 (https://drone.owncloud.com/owncloud/smashbox-testing/421): manual cancelation by @tboerger 

- failure on 1 test 11.02 (https://drone.owncloud.com/owncloud/smashbox-testing/420/244): drone timeout on oc server, transient

- failure on 1 test 10.02 (https://drone.owncloud.com/owncloud/smashbox-testing/419/550): drone timeout on oc server, transient

- failure on 1 test 9.02 : drone timeout on oc server, transient 

- failure on 1 test 8.02:  drone timeout on oc server, transient

- failure on 1 test 7.02:  drone timeout on oc server, transient

**Comment by PVince81** [comment]
ok. maybe we wait for the Drone 1.0 migration and then check if this still happens.

thanks

**Comment by mrow4a** [comment]
closing as probably not relevant any more
